spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mybatis_app_2022_09_22?serverTimezone=Asia/Seoul
    username: root
    password: 1067